apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-secrets
  namespace: {{.Values.common.namespace}}
type: Opaque
data:
{{- range $key, $value := .Values.mysql.secrets}}
  {{$key}}: {{$value | b64enc | quote}}
{{- end}}
